### ISSUE TITLE
Modules outdated wrt. Sparkler

### ISSUE THREAD

**Issue by anissen** [RudenkoArts/sparkler_modules#1]
I'm trying to update Sparkler to the latest version and in doing so I need to use `AreaEdgeSpawnModule` from this library. However, it appears to be out of sync with Sparkler. I'm getting the following error:

```
.../sparkler_modules/sparkler/modules/AreaEdgeSpawnModule.hx:10: characters 0-33 : Type not found : sparkler.utils.VectorTools
```

The file still uses Luxe vectors, for instances, so it appears to be incompatible with the latest Sparkler.

**Comment by AndreiRudenko** [comment]
Thank you, just forgot to update. I didnt test this one, but i hope it works.

**Comment by anissen** [comment]
That was very fast! It appears to work. Thank you 👍
